### ISSUE TITLE
可以增加对user-images.githubusercontent.com域名的代理吗

### ISSUE THREAD

**Issue by Vixb1122** [FastGitORG/fgit#3]

**Comment by xkeyC** [comment]
@KevinZonda

**Comment by KevinZonda** [comment]
What's it for? 😂

**Comment by KevinZonda** [comment]
能否告知我此域的用途呢？

**Comment by Vixb1122** [comment]
> 能否告知我此域的用途呢？

issue中的图片，都是这个域名的啊

**Comment by Vixb1122** [comment]
issue输入框中拖入一个图片，获取到的域名就是user-images.githubusercontent.com， @KevinZonda

**Comment by KevinZonda** [comment]
> issue输入框中拖入一个图片，获取到的域名就是user-images.githubusercontent.com， @KevinZonda 

LGTM，请到 nginx-conf repo下开一个issue
